module.exports = {
  arrowParens: "always",
  bracketSameLine: true,
  bracketSpacing: true,
  endOfLine: "lf",
  htmlWhitespaceSensitivity: "strict",
  printWidth: 80,
  proseWrap: "preserve",
  quoteProps: "as-needed",
  semi: true,
  singleAttributePerLine: false,
  singleQuote: false,
  trailingComma: "es5",
  tabWidth: 4,
  useTabs: true,
  plugins: ["prettier-plugin-tailwindcss"],
};
